version: "3.9"

services:
  bot:
    build: bot/
    container_name: python-bot
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - bridge-nerwork
  database:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    container_name: ydb-bot-database
    restart: unless-stopped
    volumes:
      - ./ydb_db/ydb_data:/ydb_data
      - ./ydb_db/ydb_certs:/ydb_certs
    ports:
      - "2135:2135"
      - "8765:8765"
      - "2136:2136"
    environment:
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
    networks:
      - bridge-nerwork
networks:
  bridge-nerwork:
    name: bridge-nerwork
    driver: bridge